/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProyectosRouteImport } from './routes/proyectos'
import { Route as ProcesoRouteImport } from './routes/proceso'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as ModulosRouteImport } from './routes/modulos'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModulosSlugRouteImport } from './routes/modulos.$slug'

const ProyectosRoute = ProyectosRouteImport.update({
  id: '/proyectos',
  path: '/proyectos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcesoRoute = ProcesoRouteImport.update({
  id: '/proceso',
  path: '/proceso',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulosRoute = ModulosRouteImport.update({
  id: '/modulos',
  path: '/modulos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulosSlugRoute = ModulosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ModulosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/modulos': typeof ModulosRouteWithChildren
  '/nosotros': typeof NosotrosRoute
  '/proceso': typeof ProcesoRoute
  '/proyectos': typeof ProyectosRoute
  '/modulos/$slug': typeof ModulosSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/modulos': typeof ModulosRouteWithChildren
  '/nosotros': typeof NosotrosRoute
  '/proceso': typeof ProcesoRoute
  '/proyectos': typeof ProyectosRoute
  '/modulos/$slug': typeof ModulosSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/modulos': typeof ModulosRouteWithChildren
  '/nosotros': typeof NosotrosRoute
  '/proceso': typeof ProcesoRoute
  '/proyectos': typeof ProyectosRoute
  '/modulos/$slug': typeof ModulosSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacto'
    | '/modulos'
    | '/nosotros'
    | '/proceso'
    | '/proyectos'
    | '/modulos/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacto'
    | '/modulos'
    | '/nosotros'
    | '/proceso'
    | '/proyectos'
    | '/modulos/$slug'
  id:
    | '__root__'
    | '/'
    | '/contacto'
    | '/modulos'
    | '/nosotros'
    | '/proceso'
    | '/proyectos'
    | '/modulos/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  ModulosRoute: typeof ModulosRouteWithChildren
  NosotrosRoute: typeof NosotrosRoute
  ProcesoRoute: typeof ProcesoRoute
  ProyectosRoute: typeof ProyectosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/proyectos': {
      id: '/proyectos'
      path: '/proyectos'
      fullPath: '/proyectos'
      preLoaderRoute: typeof ProyectosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proceso': {
      id: '/proceso'
      path: '/proceso'
      fullPath: '/proceso'
      preLoaderRoute: typeof ProcesoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modulos': {
      id: '/modulos'
      path: '/modulos'
      fullPath: '/modulos'
      preLoaderRoute: typeof ModulosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modulos/$slug': {
      id: '/modulos/$slug'
      path: '/$slug'
      fullPath: '/modulos/$slug'
      preLoaderRoute: typeof ModulosSlugRouteImport
      parentRoute: typeof ModulosRoute
    }
  }
}

interface ModulosRouteChildren {
  ModulosSlugRoute: typeof ModulosSlugRoute
}

const ModulosRouteChildren: ModulosRouteChildren = {
  ModulosSlugRoute: ModulosSlugRoute,
}

const ModulosRouteWithChildren =
  ModulosRoute._addFileChildren(ModulosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  ModulosRoute: ModulosRouteWithChildren,
  NosotrosRoute: NosotrosRoute,
  ProcesoRoute: ProcesoRoute,
  ProyectosRoute: ProyectosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
