/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProyectosRouteImport } from './routes/proyectos'
import { Route as ProcesoRouteImport } from './routes/proceso'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as ModulosRouteImport } from './routes/modulos'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as IndexRouteImport } from './routes/index'

const ProyectosRoute = ProyectosRouteImport.update({
  id: '/proyectos',
  path: '/proyectos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcesoRoute = ProcesoRouteImport.update({
  id: '/proceso',
  path: '/proceso',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulosRoute = ModulosRouteImport.update({
  id: '/modulos',
  path: '/modulos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/modulos': typeof ModulosRoute
  '/nosotros': typeof NosotrosRoute
  '/proceso': typeof ProcesoRoute
  '/proyectos': typeof ProyectosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/modulos': typeof ModulosRoute
  '/nosotros': typeof NosotrosRoute
  '/proceso': typeof ProcesoRoute
  '/proyectos': typeof ProyectosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/modulos': typeof ModulosRoute
  '/nosotros': typeof NosotrosRoute
  '/proceso': typeof ProcesoRoute
  '/proyectos': typeof ProyectosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contacto'
    | '/modulos'
    | '/nosotros'
    | '/proceso'
    | '/proyectos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contacto' | '/modulos' | '/nosotros' | '/proceso' | '/proyectos'
  id:
    | '__root__'
    | '/'
    | '/contacto'
    | '/modulos'
    | '/nosotros'
    | '/proceso'
    | '/proyectos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  ModulosRoute: typeof ModulosRoute
  NosotrosRoute: typeof NosotrosRoute
  ProcesoRoute: typeof ProcesoRoute
  ProyectosRoute: typeof ProyectosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/proyectos': {
      id: '/proyectos'
      path: '/proyectos'
      fullPath: '/proyectos'
      preLoaderRoute: typeof ProyectosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proceso': {
      id: '/proceso'
      path: '/proceso'
      fullPath: '/proceso'
      preLoaderRoute: typeof ProcesoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modulos': {
      id: '/modulos'
      path: '/modulos'
      fullPath: '/modulos'
      preLoaderRoute: typeof ModulosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  ModulosRoute: ModulosRoute,
  NosotrosRoute: NosotrosRoute,
  ProcesoRoute: ProcesoRoute,
  ProyectosRoute: ProyectosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
